### ISSUE TITLE
View context cannot be null

### ISSUE THREAD

**Issue by guikaua12** [DevNatan/inventory-framework#152] opened 2022-07-13 16:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐛 Describe the bug

Rarely when i open my menu, i get this error:
```
[13:38:32 WARN]: java.lang.IllegalStateException: View context cannot be null to Approximations in me.approximations.spawners.inventory.spawners.SpawnerMainMenu
[13:38:32 WARN]:        at me.saiintbrisson.minecraft.ViewListener.getContextOrThrow(ViewListener.java:442)
[13:38:32 WARN]:        at me.saiintbrisson.minecraft.ViewListener.onViewClick(ViewListener.java:98)
[13:38:32 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:38:32 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:38:32 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:38:32 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[13:38:32 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[13:38:32 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:38:32 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[13:38:32 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[13:38:32 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630)
[13:38:32 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
[13:38:32 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
[13:38:32 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[13:38:32 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[13:38:32 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[13:38:32 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[13:38:32 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[13:38:32 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[13:38:32 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[13:38:32 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[13:38:32 WARN]:        at java.lang.Thread.run(Unknown Source)
```

### ✔️ Expected behavior

Open the menu

### 👣 Steps to Reproduce

I really dont know how to reproduce it

### 💻 Platform

- [X] Bukkit
- [ ] Sponge
- [ ] Other

### ⭐ Version

1.8.8

**Comment by DevNatan** [comment] 2022-07-13 17:00
@guikaua12 this bug was fixed a few versions ago, wat version of IF are u using?

**Comment by DevNatan** [comment] 2022-07-13 17:02
Duplicate of #107

**Comment by guikaua12** [comment] 2022-07-13 18:15
why on lastest version of IF, ViewFrame is deprecated? how do i register my views?
![image](https://user-images.githubusercontent.com/33811154/178802856-ed6ac659-7fc3-4b4c-a9e4-6a2a2a5ccbb5.png)

**Comment by DevNatan** [comment] 2022-07-13 19:27
> and how do i open a view since there is no viewframe constructor anymore

`ViewFrame#of` will return you an ViewFrame implementation, as it was with the constructor.

The change is because the old versions of IF had no implementation distinction and from the restructuring of the code starting from v2.5.1 I was forced to prohibit the direct instantiation of the ViewFrame class since in the future it will no longer be a class and will become an interface. The change is so that in the future you don't have to change all your code, since everything is already adapted.

```java
viewFrame = ViewFrame.of(plugin, views...).register()
```

**Comment by guikaua12** [comment] 2022-07-13 19:42
how do i get the clicked itemstack?

**Comment by guikaua12** [comment] 2022-07-13 21:20
![image](https://user-images.githubusercontent.com/33811154/178838340-ab7155d3-9123-4f66-bfdd-39afa405529c.png)

**Closed** 2022-07-14 16:59 UTC
Labels: bug, duplicate

**Comment by guikaua12** [comment] 2022-07-14 17:41
Okay, one last thing, why it will be removed, it is useful

**Comment by DevNatan** [comment] 2022-07-14 17:58
> Okay, one last thing, why it will be removed, it is useful

IF provides you with the current context item in ItemStack format but the new IF API does not support this type of retrieval since the ViewSlotContext interface is in the IF shared module which is agnostic.

You will still be able to get the item from the context but it will be another way, directly accessing the platform API that will be provided in the future.

**Comment by guikaua12** [comment] 2022-07-15 01:15
Okay, thank you i think you can close this issue
