### ISSUE TITLE
Dynamic pagination cannot be accessed on user-defined layout pattern

### ISSUE THREAD

**Issue by iGabyTM** [DevNatan/inventory-framework#245] opened 2022-09-27 10:29 UTC
Hey, I need to create a paginated view that would look like this:
 ```
 ---------
<OOOOOOO>
<OOOOOOO>
<OOOOOOO>
---------
```
Where `-` is the filler, `<` and `>` are previous/next page buttons are `O` is where items would go, but I can't figure out how to that. 

This is the code used in the plugin that I try to update
```java
	@Override
    protected void onOpen(@NotNull OpenViewContext context) {
        final var config = ViewModule.getMenuConfigManager().getConfig(WarpPaginatedMenuConfig.class);
        context.setInventorySize(config.getLayout().length); // 6
        context.setInventoryTitle(config.getTitle());
        context.setLayout(config.getLayout()); // XXXXXXXXX, <OOOOOOO>, <OOOOOOO>, <OOOOOOO>, XXXXXXXXX, XXXXXXXXX
    }
    
    @Override
    protected void onRender(ViewContext context) {
        final var config = ViewModule.getMenuConfigManager().getConfig(WarpPaginatedMenuConfig.class);
        LandUser landUser = context.get("landUser");
        ViewHelper.setFillerAndDecorations(context, config);

        setSource(landUser.getWarps());

        if (landUser.getWarps().isEmpty()) {
            config.noValuesItem().forEachSlot((slot, item) -> context.slot(slot, item.getItemStack()));
        }
    }
    
    @Override
    protected void onItemRender(PaginatedViewSlotContext<LandWarp> context, ViewItem viewItem, LandWarp value) {
        final var config = ViewModule.getMenuConfigManager().getConfig(WarpPaginatedMenuConfig.class);
        Player player = context.getPlayer();

        viewItem.withItem(config.warpItem().createItem(value.createPlaceholders())).onClick(handler -> {
            if (handler.getClickOrigin().isRightClick()) {
                player.closeInventory();
                player.performCommand("land delwarp " + value.getName());
            } else if (handler.getClickOrigin().isLeftClick()) {
                player.closeInventory();
                player.performCommand("land warp " + value.getName());
            } else if (handler.getClickOrigin().getClick() == ClickType.MIDDLE) {
                value.setPublicWarp(!value.isPublicWarp());
                player.sendMessage("§aYou make this warp §f" + (value.isPublicWarp() ? "public" : "private") + "§a successfully.");

                if (value.isPublicWarp()) {
                    viewFrame.open(ChangeWarpCategoryView.class, player, ImmutableMap.of("landWarp", value));
                } else {
                    value.setCategory(LandWarpCategory.NONE);
                    player.closeInventory();
                }
            }
        });
    }
```
But the menu looks like this: 
![image](https://user-images.githubusercontent.com/32105478/192502685-d9d6da38-ab66-4364-975a-3984bf589d52.png)

If the user doesn't have any warps, it looks good:
![image](https://user-images.githubusercontent.com/32105478/192503193-e35d9744-e421-47b8-bab1-3070479fa0fa.png)

Also, I have this error when the layout doesn't have 6 rows: https://paste.helpch.at/zucofebeso.sql

**Comment by DevNatan** [comment] 2022-09-27 12:43
@iGabyTM what version of InventoryFramework are you using?

there are some remarks:
1. `setSource(landUser.getWarps())` should be `context.setSource(landUser.getWarps())`, anything called on `onRender` **must** use `context...` you are probably using an outdated version as it was supposed to give an error
2. you can use [User-Defined Patterns](https://github.com/DevNatan/inventory-framework/wiki/Pagination#user-defined-pattern-v250) to create theses fillers.
3. it's recommended to use `handler.closeUninterruptedly()` instead of `player.closeInventory()`

your code looks right, nothing except ^^ wrong, probably a bug i'll try to reproduce

**Comment by iGabyTM** [comment] 2022-09-27 13:46
The version I use is `com.github.DevNatan:inventory-framework:v2.4.2` - I know, old - but since I don't have experience with this library and the code is fairly big, I don't have enough time to fix possible bugs.
Also, I don't really want to use layout unless I have to, e.g. I can't place the pagination items on other slots otherwise or to set the items of each page in specific slots (10 - 16, 19 - 25, 28 - 34)

**Comment by DevNatan** [comment] 2022-09-27 13:53
> The version I use is `com.github.DevNatan:inventory-framework:v2.4.2` - I know, old - but since I don't have experience with this library and the code is fairly big, I don't have enough time to fix possible bugs. Also, I don't really want to use layout unless I have to, e.g. I can't place the pagination items on other slots without layout or to set the items of each page in specific slots (10 - 16, 19 - 25, 28 - 34)

Your need is real, it makes sense for me to allow paginated items to be applied in slots defined by themselves, i'll make a note of that. Anyway, there's no way i can give you a solution for an old version because there's a high chance that it has already been fixed in new versions. Try to use the newest version v2.5.4-rc.1, it and v2.5.4-beta fix many bugs previously reported it might be your case.

If it doesn't solve your problem, i'm here to help you.

**Comment by iGabyTM** [comment] 2022-09-28 06:54
![image](https://user-images.githubusercontent.com/32105478/192708631-a8f51251-4706-43df-80f3-aa1ad73d09bc.png)
```yaml
layout:
  - "---------"
  - "[OOOOOOO]"
  - "[OOOOOOO]"
  - "[OOOOOOO]"
  - "---------"
```

Looks good @DevNatan but just to make sure I do things right. I couldn't set the layout and its items on `onOpen` due to class cast conflict between BukkitOpenViewContext and PaginatedViewContext so I moved it to `onRender`.

```java
final var paginatedContext = context.paginated();
paginatedContext.setLayout(config.getLayout());
paginatedContext.setLayout('-', item -> item.setItem(config.getFiller().getItemStack()));
paginatedContext.setLayout('[', item -> item.withItem(config.previousPageItem().getItemStack()).onClick(__ -> {
    Player player = context.getPlayer();

    if (paginatedContext.isFirstPage()) {
        viewFrame.open(MainView.class, player, paginatedContext.getData());
    } else {
        paginatedContext.switchToPreviousPage();
    }
}));
paginatedContext.setLayout(']', item -> item.withItem(config.nextPageItem().getItemStack()).onClick(__ -> paginatedContext.switchToNextPage()));```

**Comment by iGabyTM** [comment] 2022-09-28 07:30
So I've made this util class to load the layout because I will use a similar system on multiple menus that are paginated
```java
public void setPaginationItems(
        @NotNull final PaginatedViewContext<Object> context, @NotNull final PaginatedMenuConfig config,
        @NotNull final Consumer<ViewSlotClickContext> previousPageClickHandler, @NotNull final Consumer<ViewSlotClickContext> nextPageClickHandler
) {
    context.setLayout(config.getLayout());
    context.setLayout('-', item -> item.setItem(config.getFiller().getItemStack()));
    context.setLayout('[', item -> item.withItem(config.previousPageItem(context.hasPreviousPage()).getItemStack()).onClick(previousPageClickHandler));
    context.setLayout(']', item -> item.withItem(config.nextPageItem(context.hasNextPage()).getItemStack()).onClick(nextPageClickHandler));
}
```
But this https://paste.helpch.at/lakaqeqawu.rb error is thrown by `context.hasNextPage()` (I use this and `context.hasPreviousPage` to check what item I should use, nextPage/previousPage or noNextPage/noPreviousPage)
Though, I set the source on the constructor, so idk why it would be null
`setSource(context -> ((LandUser) context.get("landUser")).getWarps());`

**Comment by DevNatan** [comment] 2022-09-28 15:02
Hmm, ok @iGabyTM I understand why this happens, the [pagination interceptor](https://github.com/DevNatan/inventory-framework/blob/50c26f53a2053e7ecfbac003105850fcd252d403/shared/src/main/java/me/saiintbrisson/minecraft/pipeline/interceptors/PaginationRenderInterceptor.java#L29) comes after the [layout resolution interceptor](https://github.com/DevNatan/inventory-framework/blob/50c26f53a2053e7ecfbac003105850fcd252d403/shared/src/main/java/me/saiintbrisson/minecraft/pipeline/interceptors/LayoutResolutionInterceptor.java#L37) so pagination I'll not be available on user-defined layout pattern. it's the first time I've been reported this so it's a bug, I'll change the order of the interceptors to make this possible

**Comment by iGabyTM** [comment] 2022-09-28 15:12
Any idea when a fix will be released? I kind need this soon 😅

**Comment by DevNatan** [comment] 2022-09-28 15:14
> Any idea when a fix will be released? I kind need this soon 😅

Today or tomorrow, don't worry, it's literally just swapping one line for another. And you will still be able to use the fix before I release the version, using a specific build version that I will upload here

**Comment by iGabyTM** [comment] 2022-09-29 12:24
@DevNatan is possible to set the source on `onOpen`? I need to filter some lists and combine the result, then I need to know if the final list has any object and set it as a context variable which I access later on `onRender`

**Comment by DevNatan** [comment] 2022-09-29 17:08
> @DevNatan is possible to set the source on `onOpen`? I need to filter some lists and combine the result, then I need to know if the final list has any object and set it as a context variable which I access later on `onRender`. Calling `context.paginated()` throws a class cast exception because BukkitOpenViewContext can not be casted as a PaginatedViewContext.

You can do this in onRender, it's only called once.

It is not possible to set the pagination data in onOpen because nothing was dealt with at that point, it is only used to prepopulate inventory information like title and size or cancel its opening, but yes, you can define context data in onOpen and they will be accessible in onRender.

It is common to do this type of code to save computation
```kotlin
fun onOpen(ctx: ViewContext) {
    val profile = getProfileSomehow<Profile>("iGabyTM")
    
    ctx.setInventoryTitle("Profile of %s".format(profile.owner))
    ctx.set("profile", profile)
}

fun onRender(ctx: ViewContext) {
    val profile = ctx.get<Profile>("profile")
    
    ctx.paginated().setSource(() -> profile.getStatistics() /* imagine this is a list */)
}
```

**Comment by DevNatan** [comment] 2022-09-30 14:43
@iGabyTM Please try to use `4ba907ff90` version and check if your bug was fixed also if you need a executable plugin, get it here https://github.com/DevNatan/inventory-framework/actions/runs/3153688855 (#248) (scroll down to Artifacts)

**Comment by iGabyTM** [comment] 2022-09-30 17:04
Will test this version a bit later, thank you!

**Comment by iGabyTM** [comment] 2022-10-01 17:22
Hmm, so with this layout and 2 items to show, it displays the "no next page" item @DevNatan.
```yaml
layout:
  - "---------"
  - "[---O---]"
  - "---------"
```
![image](https://user-images.githubusercontent.com/32105478/193420930-cc8b61ae-c785-42d7-9a5e-57ae52d5b0fd.png)


```sql
[20:18:04 INFO]: [ClaimCommons] [STDOUT] called pattern get factory ViewItem(item=ItemStack{GRAY_STAINED_GLASS_PANE x 1, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name={"extra":[{"text":" "}],"text":""}, custom-model-data=0}}, slot=-1, state=UNDEFINED, paginationItem=false, navigationItem=false, referenceKey=null, closeOnClick=false, cancelOnClick=false, cancelOnShiftClick=false, renderHandler=null, updateHandler=null, clickHandler=null, moveInHandler=null, moveOutHandler=null, itemHoldHandler=null, itemReleaseHandler=null, data=null, updateIntervalInTicks=-3, overlay=null, removed=false)
[20:18:04 INFO]: [ClaimCommons] [STDOUT] called pattern get factory ViewItem(item=ItemStack{RED_STAINED_GLASS_PANE x 1, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name={"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"Previous Menu"}],"text":""}, custom-model-data=0}}, slot=-1, state=UNDEFINED, paginationItem=false, navigationItem=false, referenceKey=null, closeOnClick=false, cancelOnClick=false, cancelOnShiftClick=false, renderHandler=null, updateHandler=null, clickHandler=me.gabytm.minecraftc.claimcommons.menu.util.ViewUtil$$Lambda$7295/0x0000000801fcf088@120cc078, moveInHandler=null, moveOutHandler=null, itemHoldHandler=null, itemReleaseHandler=null, data=null, updateIntervalInTicks=-3, overlay=null, removed=false)
[20:18:04 INFO]: [ClaimCommons] [STDOUT] called pattern get factory ViewItem(item=ItemStack{BLACK_STAINED_GLASS_PANE x 1, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name={"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"No Next Page"}],"text":""}, custom-model-data=0}}, slot=-1, state=UNDEFINED, paginationItem=false, navigationItem=false, referenceKey=null, closeOnClick=false, cancelOnClick=false, cancelOnShiftClick=false, renderHandler=null, updateHandler=null, clickHandler=me.gabytm.minecraftc.claimcommons.menu.util.ViewUtil$$Lambda$7296/0x0000000801fcf2b8@e9023e9, moveInHandler=null, moveOutHandler=null, itemHoldHandler=null, itemReleaseHandler=null, data=null, updateIntervalInTicks=-3, overlay=null, removed=false)
```

**Comment by DevNatan** [comment] 2022-10-01 19:36
> Hmm, so with this layout and 2 items to show, it displays the "no next page" item @DevNatan.
> 
> ...

@iGabyTM are you using setLayout with "onRender" or without?

setLayout is a factory, it is only called once on Layout Resolution pipeline phase and applied to context, later Render pipeline phase reuse this manufactured value, so it will always be the same item.

when an update occurs (like change page), only dynamic items (that have `onRender` or `onUpdate`) will be re-computed for performance reasons so it is necessary to use them.

So if you use, this way nothing will happen since this function is just a factory and not a computed value
```java
context.setLayout('[', item -> item.withItem(
    context.paginated().hasNextPage() ? A : B
))
```

to make your item become dynamic and react to updates such as page switches you need to use the render function
```java
// on constructor
setLayout('[', item -> item.onRender(render -> render.setItem(
  context.paginated().hasNextPage() ? A : B
)))
```

you can also use the `rendered` shortcut if you already have access to the context
```java
// on "onRender"
context.setLayout('[', item -> item.rendered(() ->
  context.paginated().hasNextPage() ? A : B
))
```

**Comment by iGabyTM** [comment] 2022-10-02 15:13
```java
public static void setPaginationItems(
        @NotNull final PaginatedViewContext<Object> context, @NotNull final PaginatedMenuConfig config,
        @NotNull final Consumer<ViewSlotClickContext> previousPageClickHandler, @NotNull final Consumer<ViewSlotClickContext> nextPageClickHandler
) {
    context.setLayout(config.getLayout());
    context.setLayout('-', item -> item.setItem(config.getFiller().getItemStack()));
    context.setLayout('[', item ->
            item.rendered(() -> config.previousPageItem(context.hasPreviousPage()).getItemStack())
                    .onClick(previousPageClickHandler)
    );
    context.setLayout(']', item ->
            item.rendered(() -> config.nextPageItem(context.hasNextPage()).getItemStack())
                    .onClick(nextPageClickHandler)
    );
}
```
So I call this method on `onRender` and I still see the `no next page` item 😕

**Comment by iGabyTM** [comment] 2022-10-02 16:48
Also, is this some debugging left in code?
```
[20:18:04 INFO]: [ClaimCommons] [STDOUT] called pattern get factory ViewItem(item=ItemStack{GRAY_STAINED_GLASS_PANE x 1, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name={"extra":[{"text":" "}],"text":""}, custom-model-data=0}}, slot=-1, state=UNDEFINED, paginationItem=false, navigationItem=false, referenceKey=null, closeOnClick=false, cancelOnClick=false, cancelOnShiftClick=false, renderHandler=null, updateHandler=null, clickHandler=null, moveInHandler=null, moveOutHandler=null, itemHoldHandler=null, itemReleaseHandler=null, data=null, updateIntervalInTicks=-3, overlay=null, removed=false)
[20:18:04 INFO]: [ClaimCommons] [STDOUT] called pattern get factory ViewItem(item=ItemStack{RED_STAINED_GLASS_PANE x 1, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name={"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"Previous Menu"}],"text":""}, custom-model-data=0}}, slot=-1, state=UNDEFINED, paginationItem=false, navigationItem=false, referenceKey=null, closeOnClick=false, cancelOnClick=false, cancelOnShiftClick=false, renderHandler=null, updateHandler=null, clickHandler=me.gabytm.minecraftc.claimcommons.menu.util.ViewUtil$$Lambda$7295/0x0000000801fcf088@120cc078, moveInHandler=null, moveOutHandler=null, itemHoldHandler=null, itemReleaseHandler=null, data=null, updateIntervalInTicks=-3, overlay=null, removed=false)
[20:18:04 INFO]: [ClaimCommons] [STDOUT] called pattern get factory ViewItem(item=ItemStack{BLACK_STAINED_GLASS_PANE x 1, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name={"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"No Next Page"}],"text":""}, custom-model-data=0}}, slot=-1, state=UNDEFINED, paginationItem=false, navigationItem=false, referenceKey=null, closeOnClick=false, cancelOnClick=false, cancelOnShiftClick=false, renderHandler=null, updateHandler=null, clickHandler=me.gabytm.minecraftc.claimcommons.menu.util.ViewUtil$$Lambda$7296/0x0000000801fcf2b8@e9023e9, moveInHandler=null, moveOutHandler=null, itemHoldHandler=null, itemReleaseHandler=null, data=null, updateIntervalInTicks=-3, overlay=null, removed=false)
```

**Comment by iGabyTM** [comment] 2022-10-07 21:40
Hey @DevNatan any idea?

**Comment by DevNatan** [comment] 2022-10-09 20:01
> Hey @DevNatan any idea?

sorry for the late reply, i'm traveling, try updating to the [latest version](https://github.com/DevNatan/inventory-framework/actions/runs/3165915040) to see if your issue is resolved

**Comment by iGabyTM** [comment] 2022-11-21 22:50
> ```java
> public static void setPaginationItems(
>         @NotNull final PaginatedViewContext<Object> context, @NotNull final PaginatedMenuConfig config,
>         @NotNull final Consumer<ViewSlotClickContext> previousPageClickHandler, @NotNull final Consumer<ViewSlotClickContext> nextPageClickHandler
> ) {
>     context.setLayout(config.getLayout());
>     context.setLayout('-', item -> item.setItem(config.getFiller().getItemStack()));
>     context.setLayout('[', item ->
>             item.rendered(() -> config.previousPageItem(context.hasPreviousPage()).getItemStack())
>                     .onClick(previousPageClickHandler)
>     );
>     context.setLayout(']', item ->
>             item.rendered(() -> config.nextPageItem(context.hasNextPage()).getItemStack())
>                     .onClick(nextPageClickHandler)
>     );
> }
> ```
> 
> So I call this method on `onRender` and I still see the `no next page` item 😕

Hey @DevNatan, I've updated to ae6b07b0b98ce1233f5c9fb0cdb10a64c8d68864 and I'm still not able to get this code working, any ideas?

**Comment by DevNatan** [comment] 2022-11-22 14:33
@iGabyTM i already found the problem, the pagination source check is not compatible with dynamic or asynchronous pagination yet, i already prepared a fix for this should be in main branch soon.

**Comment by DevNatan** [comment] 2022-11-22 15:46
@iGabyTM I tried to reproduce your code and it worked. Try using the version of #254 and see if it gives any problems

```java
class Test extends PaginatedView<Integer> {

    public Test() {
        super(3);
        setSource($ -> IntStream.rangeClosed(1, 100).boxed().collect(Collectors.toList()));
    }

    @Override
    protected void onRender(@NotNull ViewContext context) {
        context.setLayout("XXXXXXXXX", "[OOOOOOO]", "XXXXXXXXX");
        context.setLayout(']', item -> {
            item.rendered(() -> {
                // breakpoint maybe
                context.paginated().hasPreviousPage();
                return new ItemStack(Material.ARROW);
            });
        });
        context.setLayout('[', item -> {
            item.rendered(() -> {
                // breakpoint maybe
                context.paginated().hasNextPage();
                return new ItemStack(Material.ARROW);
            });
        });
    }

    @Override
    protected void onItemRender(
            @NotNull PaginatedViewSlotContext<Integer> context, @NotNull ViewItem viewItem, @NotNull Integer value) {
        viewItem.withItem(new ItemStack(Material.DIAMOND));
    }
}
```

**Comment by iGabyTM** [comment] 2022-11-23 15:36
Huh, how do I use that version?

**Comment by iGabyTM** [comment] 2022-11-23 16:03
I got it, thanks. I've tried the same code as yours and I still can't see the next page button..

**Comment by DevNatan** [comment] 2022-11-23 16:05
> I got it, thanks. I've tried the same code as yours and I still can't see the next page button..

are you getting an error or is the code just not working?

**Comment by iGabyTM** [comment] 2022-11-23 16:09
No, I'm not getting errors. Is there a method I can use to check how many items fit in a page?

**Comment by DevNatan** [comment] 2022-11-23 16:18
> No, I'm not getting errors. Is there a method I can use to check how many items fit in a page? I see that you are testing with 100 items and I got only a small amount of items

few, but some are only accurate if you have context available, u can use `getSource().size()`, `getPageSize()` or `getPageMaxItemsCount()` they have slightly different behaviors, in the documentation it is written what each one returns maybe it can be useful.

**Comment by DevNatan** [comment] 2022-11-23 16:33
> `context.paginated().getPageSize() = 44`, the default size is set to 5 trough the super() constructor but on `onOpen` I have `context.setContainerSize(config.getLayout().length);` And I can't access `getPageMaxItemsCount()` because of this error https://paste.helpch.at/topafevago.rb

weird, layout resolution should happen before rendering and this error shouldn't happen. Apparently the values are wrong due to the definition of the container in onOpen, i'll analyze

**Comment by iGabyTM** [comment] 2022-12-17 19:11
Hey @DevNatan any updates?

**Comment by WizWazWizard** [comment] 2022-12-24 19:35
Any Updates on the matter? Need this fixed asap :/

**Comment by iGabyTM** [comment] 2023-01-10 21:47
@DevNatan 😬

**Comment by iGabyTM** [comment] 2023-01-27 22:24
@DevNatan do you think you can update us on this? :(

**Comment by iGabyTM** [comment] 2023-02-22 17:32
@DevNatan ?

**Comment by DevNatan** [comment] 2023-03-04 14:35
@iGabyTM we have a major version under development, this issue is already planned to be fixed in v3.0.0, I don't have time to code inventory-framework lately so please be patient, i'm doing the best i can. more info will come soon

**Comment by WizWazWizard** [comment] 2023-03-31 23:54
> @iGabyTM we have a major version under development, this issue is already planned to be fixed in v3.0.0, I don't have time to code inventory-framework lately so please be patient, i'm doing the best i can. more info will come soon.
> 
> and I will also give you a mirror code from your version to the new version since some things have changed

Any luck on this???

**Comment by DevNatan** [comment] 2023-04-01 17:27
> > @iGabyTM we have a major version under development, this issue is already planned to be fixed in v3.0.0, I don't have time to code inventory-framework lately so please be patient, i'm doing the best i can. more info will come soon.
> > and I will also give you a mirror code from your version to the new version since some things have changed
> 
> Any luck on this???

Expected to be released in the first week of April, code itself appears to be finished there are still some tests left. I'm just finishing up fully updating the [Wiki](Wiki) before releasing it.

**Comment by iGabyTM** [comment] 2023-05-01 18:29
@DevNatan I don't want to be rude but it is 1st of May, any news on the update?

**Comment by DevNatan** [comment] 2023-05-13 14:47
> @DevNatan I don't want to be rude but it is 1st of May, any news on the update?

Yes, there was a 3.0.0 version, but several problems were found mainly in relation to the integration in projects of different JDKs since the entire Inventory Framework project was updated, which is already being resolved.

Some features that existed in the previous version and would not exist more in this new version will be brought back, some people complained about it.

There is a todo roadmap for a preview release or beta #370

**Comment by DevNatan** [comment] 2023-06-08 02:07
> > 
> 
> Any luck? Been waiting 3 months for this one fix :/

Yeah, [v3.0.0-EAP](https://github.com/DevNatan/inventory-framework/releases/tag/v3.0.0-EAP) is available but not production ready. But I will keep this issue open until the definitive v3.0.0 is released.

**Comment by WizWazWizard** [comment] 2023-06-23 12:10
Awesome! Could you add me on discord so I can give you direct contact with a developer? Mainly to look over the changes in the library :)

Discord: silenttail

**Comment by iGabyTM** [comment] 2023-06-23 13:56
@DevNatan I've noticed that the version that contains the fix for this issue is a major release with a lot of API changes. I was wondering if you could help us fix the issue without updating to v3 because that involves a lot of work to update all the menus we have.
I'm not experienced enough with this library, I just continue the work of another developer that I sadly can not contact. Is there any way to create some sort of _fake_ pagination with normal GUIs, where each page is a different GUI?

**Comment by WizWazWizard** [comment] 2023-07-09 12:23
DevNatan?

**Comment by WizWazWizard** [comment] 2023-08-26 15:20
Hiya, an luck? Been an extra month and I haven't heard or seen any updates around this issue?
I understand you may be busy, but this issue was reported on Sep 27, 2022. Its now August 26th 2023, almost a whole year?

**Comment by WizWazWizard** [comment] 2023-11-27 17:11
> > > 
> > 
> > 
> > Any luck? Been waiting 3 months for this one fix :/
> 
> Yeah, [v3.0.0-EAP](https://github.com/DevNatan/inventory-framework/releases/tag/v3.0.0-EAP) is available but not production ready. But I will keep this issue open until the definitive v3.0.0 is released.

This is kinda ridiculous.. Its almost been 2 years..

**Comment by DevNatan** [comment] 2023-11-27 17:22
Please update to version 3. It is extremely similar and simpler. I no longer support version 2

**Closed by DevNatan** 2023-11-27 17:22 UTC
Labels: bug, confirmed
